- looper/looper.py
> Add support for several figures per sample in figure summary

- .gitignore
- looper/pipeline_interface.py
- looper/project.py
> Ensure protocol mapping key consistency

- looper/__init__.py
> Skip null location entries

- doc/source/changelog.rst
- looper/_version.py
- looper/html_reports.py
- looper/looper.py
- looper/pipeline_interface.py
- looper/project.py
- requirements/requirements-all.txt
- tests/conftest.py
- tests/models/conftest.py
- tests/models/test_PipelineInterface.py
- Reflect removal of  `alpha_cased` for stricter protocol matching
- Update `ProjectContext` call to reflect signature on powerful sample fetching function from @michalstolarczyk
- Use `attmap`
> Use new peppy API and attmap

- looper/looper.py
- looper/pipeline_interface.py
- looper/project.py
- looper/submission_manager.py
- looper/utils.py
@nsheff I went with "whisper." I liked that but fine w/ changing if you prefer an alternative.
> Improve custom logging

- looper/conductor.py
- looper/looper.py
- looper/pipeline_interface.py
> Write submission scripts whenever possible

- looper/__init__.py
- looper/looper.py
- looper/pipeline_interface.py
- requirements/requirements-all.txt
> Custom compute

- looper/utils.py
Keeping `jinja` synced up with `dev` changes
> Dev into jinja

- looper/jinja_templates/object.html
> make links on object pages to pdfs

- looper/__init__.py
- looper/conductor.py
- looper/looper.py
- looper/project.py
- looper/schemas/pipeline_interface_schema.yaml
- subdivide summarize function
- create Table(): generates stats_summary and objs_summary data and writes to disk (optionally)
- create Report(): requires Table(), but can optionally not write to disk and masks the call
- Report() can include `--no-table` and will *not* write stats and obj summary files to disk
> Split 'summarize'

- looper/__init__.py
- looper/conductor.py
- looper/const.py
- tests/data/pipeline_interface2_sample.yaml
- tests/smoketests/conftest.py
- tests/smoketests/test_run.py
output `namespaces` into .yaml file #298
> namespaces output plugin

- .gitignore
- looper/__init__.py
- looper/const.py
- looper/looper.py
- looper/utils.py
Add ability to create a generic pipeline interface by using:
looper init -p
or
looper init --pipeline
close #327
> Add ability to create a generic pipeline interface

- looper/__init__.py
- looper/looper.py
- looper/utils.py
- looper config file argument was edded
> added looper config file argument

- bash_complete.sh
- docs/advanced.md
- docs/changelog.md
- looper/cli_looper.py
Adds basic tab completion for #422
> tab completion

- docs/README.md
- requirements/requirements-test.txt
> Lower bound hypothesis version

- looper/cli_looper.py
- looper/looper.py
Adds`--portable` flag for #442
> add portable flag to looper report

- docs/changelog.md
- looper/cli_looper.py
- looper/conductor.py
- looper/looper.py
- tests/smoketests/test_run.py
Closes https://github.com/pepkit/looper/issues/415
> Change lump parameters, add --lump-j

- looper/divvy.py
- tests/smoketests/test_run.py
This was supposedly already done, but there were still some vestiages of attmap in divvy. This finishes and polishes divvy a bit.
> finish removing attmap from divvy

- looper/cli_pydantic.py
- looper/command_models/commands.py
- looper/utils.py
- tests/smoketests/test_other.py
Addresses: https://github.com/pepkit/looper/issues/462
> Dev fix inspect

- looper/project.py
- tests/smoketests/test_run.py
> potential fix for attribute error when inferring project name when loading from csv

- looper/conductor.py
- looper/pipeline_interface.py
- looper/plugins.py
- looper/utils.py
> add hierarchical var_templates #334

- looper/cli_pydantic.py
- looper/command_models/arguments.py
- looper/command_models/commands.py
- looper/const.py
- looper/project.py
- looper/utils.py
- requirements/requirements-all.txt
Addresses https://github.com/pepkit/looper/issues/270
> Dev add sample mods looperconfig 270

- looper/cli_pydantic.py
- looper/const.py
- looper/utils.py
Addresses #465, maintains backwards compatibility
> infer pipeline_type directly from interface

- looper/cli_pydantic.py
- looper/const.py
- looper/project.py
- looper/utils.py
Refactor `cli_modifiers` to `cli`
Revert adding `sample_modifiers` to looper config for now
#270
> Dev 270 rework

- docs/changelog.md
- looper/_version.py
- looper/cli_pydantic.py
- requirements/requirements-all.txt
- ensure peppy requirement peppy>=0.40.0,<=0.40.2
> v1.9.1 release

- docs/changelog.md
- looper/_version.py
- looper/cli_pydantic.py
- requirements/requirements-test.txt
- Remove veracitools dependency from the requirements.
> Release v2.0.2
